export const QUOTES = [
  'El progreso se construye con foco sostenido.',
  'Lo importante rara vez es urgente, pero siempre merece tiempo.',
  'Un buen plan hoy vale mas que uno perfecto manana.',
  'La claridad convierte trabajo pendiente en trabajo posible.',
  'La constancia gana cuando la motivacion cambia.',
  'Cada pequeno avance confirma que el camino sigue abierto.',
  'La disciplina hace simple lo que la duda vuelve pesado.',
  'Una tarea terminada pesa menos que una idea postergada.',
  'El esfuerzo silencioso tambien construye resultados visibles.',
  'Ordenar el dia es empezar a ganar la batalla.',
  'La mejora real nace de repetir bien lo importante.',
  'No hace falta correr, hace falta no abandonar.',
  'El foco protege tu energia de lo que no suma.',
  'Cada decision clara reduce el ruido del camino.',
  'La paciencia convierte procesos largos en logros firmes.',
  'El trabajo bien hecho siempre deja una huella.',
  'Avanzar poco sigue siendo avanzar.',
  'La excelencia empieza cuando haces bien lo basico.',
  'El compromiso sostiene lo que la emocion inicia.',
  'Una mente ordenada encuentra mejores soluciones.',
  'La accion vence a la preocupacion cuando empieza temprano.',
  'El descanso tambien forma parte de un buen rendimiento.',
  'Hoy no tiene que ser perfecto, tiene que contar.',
  'La perseverancia transforma intentos en experiencia.',
  'Quien cuida su foco cuida su futuro.',
  'Las metas grandes se obedecen en pasos pequenos.',
  'La calma permite decidir mejor que la prisa.',
  'La responsabilidad de hoy es la libertad de manana.',
  'La practica constante vuelve natural lo dificil.',
  'Cada dia ordenado acerca una version mas fuerte de vos.',
  'Hacer lo correcto en silencio tambien es avanzar.',
  'La energia vuelve cuando el proposito esta claro.',
  'Un paso firme vale mas que diez promesas.',
  'La confianza crece cuando cumplis lo que dijiste.',
  'Lo dificil se achica cuando lo dividis en partes.'
];